- hosts: all
  vars_files: [osx_defaults.yml]
  tasks:
    - name: Clone Alfalfa repo to ~/.alfalfa
      git:
        repo: https://github.com/seattle-beach/alfalfa.git
        dest: ~/.alfalfa
        version: wip
      tags: [debug]

    - name: Symlink Bash it
      file: src=~/.alfalfa/.bash_it dest=~/.bash_it state=link

    - name: Create directories for enabling Bash it features
      file: path=~/.bash_it/{{ item }}/enabled state=directory
      with_items: [aliases, completion, plugins]

    - name: Enable Bash it features
      file: src=~/.bash_it/{{ item.key }} dest=~/.bash_it/{{ item.value }} state=link
      with_dict:
        aliases/available/general.aliases.bash: aliases/enabled/general.aliases.bash
        completion/available/defaults.completion.bash: completion/enabled/defaults.completion.bash
        completion/available/git.completion.bash: completion/enabled/git.completion.bash
        plugins/available/ssh.plugin.bash: plugins/enabled/ssh.plugin.bash

    - name: Symlink all the things!
      file: src=~/.alfalfa/{{ item.key }} dest={{ item.value }} state=link force=yes
      with_dict:
        .bash_profile: ~/.bash_profile
        iterm2/com.googlecode.item2.plist: ~/Library/Preferences/com.googlecode.iterm2.plist

    - name: Install formulae
      homebrew: name={{ item }} state=present
      with_items:
        - ctags-exuberant
        - ag
        - chromedriver
        - imagemagick
        - node
        - pstree
        - qt
        - ssh-copy-id
        - tmux
        - tree
        - watch
        - wget
        - rbenv-binstubs

    - name: Install casks
      homebrew_cask: name={{ item }} state=present
      with_items:
        - firefox
        - flycut
        - rowanj-gitx
        - github-desktop
        - google-chrome
        - google-drive
        - google-hangouts
        - macvim
        - shiftit
        - skype
        - textmate
        - vagrant
        - virtualbox
        - xquartz
        - xscope

    - name: Add ShiftIt to login items
      command: ~/.alfalfa/bin/addLoginItem ~/Applications/ShiftIt.app
      become: yes
      become_user: "{{ ansible_env.USER }}"

    - name: Check if ShiftIt is enabled in Accessibility whitelist
      shell: echo "SELECT allowed FROM access WHERE client = 'org.shiftitapp.ShiftIt';" | sqlite3 /Library/Application\ Support/com.apple.TCC/TCC.db
      become: yes
      register: shiftit_out

    - name: Add ShiftIt to Accessibility whitelist
      shell: echo "INSERT INTO access VALUES('kTCCServiceAccessibility','org.shiftitapp.ShiftIt',0,1,1,NULL);" | sqlite3 /Library/Application\ Support/com.apple.TCC/TCC.db
      become: yes
      when: not shiftit_out.stdout

    - name: Enable ShiftIt in Accessiblity whitelist
      shell: echo "UPDATE access SET allowed = 1 WHERE client = 'org.shiftitapp.ShiftIt';" | sqlite3 /Library/Application\ Support/com.apple.TCC/TCC.db
      become: yes
      when: shiftit_out.stdout and shiftit_out.stdout != "1"

    - name: Set OS X defaults
      osx_defaults:
        domain: "{{ item.domain | default(omit) }}"
        key: "{{ item.key }}"
        type: "{{ item.type }}"
        value: "{{ item.value }}"
      with_items: osx_defaults
      tags: [debug]
