- hosts: all
  tasks:
    - name: Tap Homebrew repositories
      homebrew_tap: tap={{ item }}
      with_items:
        - caskroom/fonts
        - cloudfoundry/tap
        - pivotal/tap

    - name: Update Homebrew
      homebrew: update_homebrew=yes

    - name: Install Homebrew formulae
      homebrew: name={{ item }}
      with_items:
        - ag
        - ansible
        - cf-cli
        - cowsay
        - direnv
        - git
        - git-pair
        - gti
        - rbenv
        - tmux
        - watch

    - name: Authenticate sudo for app installations
      ping:
      become: yes

    - name: Install Homebrew casks
      homebrew_cask: name={{ item }}
      with_items:
        - flycut
        - font-hack
        - font-sauce-code-powerline
        - font-source-code-pro
        - google-chrome
        - iterm2
        - lastpass
        - macvim
        - shiftit

    - name: Install gi
      get_url: url=https://github.com/sgravrock/gi/releases/download/0.0.1/gi-0.0.1-macosx dest=/usr/local/bin/gi mode=0755

    - name: Update OS X defaults
      my_defaults:
        domain: "{{ item.domain | default(omit) }}"
        key: "{{ item.key }}"
        type: "{{ item.type }}"
        value: "{{ item.value }}"
      with_items:
        - # Set default Terminal theme to Pro
          domain: com.apple.Terminal
          key: Default Window Settings
          type: string
          value: Pro
        - # Set default Terminal theme to Pro
          domain: com.apple.Terminal
          key: Startup Window Settings
          type: string
          value: Pro
        - # Autohide the Dock
          domain: com.apple.dock
          key: autohide
          type: bool
          value: true
        - # Put the Dock on the left
          domain: com.apple.dock
          key: orientation
          type: string
          value: left
        - # keyboard repeat rate
          key: KeyRepeat
          type: int
          value: 1
        - # delay before keyboard repeat
          key: InitialKeyRepeat
          type: int
          value: 15

    - name: Install dockutil
      homebrew: name=dockutil
    - name: Remove all icons from the Dock
      command: dockutil --remove all
      environment:
        PATH: "/usr/local/bin:/Users/{{ ansible_env.USER }}/.rbenv/shims:{{ ansible_env.PATH }}"
    - name: Uninstall dockutil
      homebrew: name=dockutil state=absent
    - name: Restart the Dock
      command: killall Dock
      ignore_errors: yes

    - name: Set login items
      command: ~/source/alfalfa/bin/addLoginItem /Applications/{{ item }}.app
      become: yes
      become_user: "{{ ansible_env.USER }}"
      with_items:
        - Flycut
        - ShiftIt

    - name: Check if ShiftIt is enabled in Accessibility whitelist
      shell: echo "SELECT allowed FROM access WHERE client = 'org.shiftitapp.ShiftIt';" | sqlite3 /Library/Application\ Support/com.apple.TCC/TCC.db
      become: yes
      register: shiftit_out
    - name: Add ShiftIt to Accessibility whitelist
      shell: echo "INSERT INTO access VALUES('kTCCServiceAccessibility','org.shiftitapp.ShiftIt',0,1,1,NULL,NULL);" | sqlite3 /Library/Application\ Support/com.apple.TCC/TCC.db
      become: yes
      when: not shiftit_out.stdout
    - name: Enable ShiftIt in Accessiblity whitelist
      shell: echo "UPDATE access SET allowed = 1 WHERE client = 'org.shiftitapp.ShiftIt';" | sqlite3 /Library/Application\ Support/com.apple.TCC/TCC.db
      become: yes
      when: shiftit_out.stdout and shiftit_out.stdout != "1"

    - name: Start OS X apps
      shell: pgrep "{{ item.key }}" || open -a "{{ item.value }}"
      with_dict:
        ShiftIt: ShiftIt.app
