- hosts: all
  tasks:
    - name: Clone Alfalfa repo to ~/.alfalfa
      git:
        repo: https://github.com/seattle-beach/alfalfa.git
        dest: ~/.alfalfa
        version: wip

    - name: Symlink Bash it
      file: src=~/.alfalfa/.bash_it dest=~/.bash_it state=link

    - name: Create directories for enabling Bash it features
      file: path=~/.bash_it/{{ item }}/enabled state=directory
      with_items: [aliases, completion, plugins]

    - name: Enable Bash it features
      file: src=~/.bash_it/{{ item.key }} dest=~/.bash_it/{{ item.value }} state=link
      with_dict:
        aliases/available/general.aliases.bash: aliases/enabled/general.aliases.bash
        completion/available/defaults.completion.bash: completion/enabled/defaults.completion.bash
        completion/available/git.completion.bash: completion/enabled/git.completion.bash
        plugins/available/ssh.plugin.bash: plugins/enabled/ssh.plugin.bash

    - name: Symlink all the things!
      file: src=~/.alfalfa/{{ item.key }} dest={{ item.value }} state=link force=yes
      with_dict:
        .bash_profile: ~/.bash_profile
        iterm2/com.googlecode.item2.plist: ~/Library/Preferences/com.googlecode.iterm2.plist

    - name: Install formulae
      homebrew: name={{ item }} state=present
      with_items:
        - ctags-exuberant
        - ag
        - chromedriver
        - imagemagick
        - node
        - pstree
        - qt
        - ssh-copy-id
        - tmux
        - tree
        - watch
        - wget
        - rbenv-binstubs

    - name: Install casks
      homebrew_cask: name={{ item }} state=present
      with_items:
        - firefox
        - flycut
        - rowanj-gitx
        - github-desktop
        - google-chrome
        - google-drive
        - google-hangouts
        - macvim
        - shiftit
        - skype
        - textmate
        - vagrant
        - virtualbox
        - xquartz
        - xscope

    - name: Download addloginitem to /usr/local/bin
      command: 
      tags: [debug]

    - name: Download addloginitem to /usr/local/bin
      get_url:
        url: https://github.com/downloads/pivotalexperimental/addLoginItem/addLoginItem 
        dest: /usr/local/bin/addLoginItem
        mode: 0755
        validate_certs: no
