- hosts: all
  vars:
  tasks:
    - name: Clone Alfalfa repo to ~/.alfalfa
      git:
        repo: https://github.com/seattle-beach/alfalfa.git
        dest: ~/.alfalfa
        version: wip

    - name: Clone Bash it to ~/.bash_it
      git:
        repo: https://github.com/Bash-it/bash-it.git
        dest: ~/.bash_it

    - name: Create directories for enabling Bash it features
      file: path=~/.bash_it/{{ item }}/enabled state=directory
      with_items: [aliases, completion, plugins]

    - name: Enable Bash it features
      file: src=~/.bash_it/{{ item.key }} dest=~/.bash_it/{{ item.value }} state=link
      with_dict:
        aliases/available/general.aliases.bash: aliases/enabled/general.aliases.bash
        completion/available/defaults.completion.bash: completion/enabled/defaults.completion.bash
        completion/available/git.completion.bash: completion/enabled/git.completion.bash
        plugins/available/ssh.plugin.bash: plugins/enabled/ssh.plugin.bash

    - name: Symlink all the things!
      file: src=~/.alfalfa/{{ item.key }} dest={{ item.value }} state=link force=yes
      with_dict:
        .bash_profile: ~/.bash_profile
